import { Product } from '@/types/product';

export const PLACEHOLDER_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Linen Blend Blouse',
    price: 899,
    image: '/images/products/linen-blend-blouse.jpg',
    category: 'Tops',
    condition: 'Like New',
    size: 'Size M',
    isNewEdit: true,
  },
  {
    id: 'prod-2',
    name: 'Classic Knit Sweater',
    price: 1199,
    image: '/images/products/classic-knit-sweater.jpg',
    category: 'Outerwear',
    condition: 'Excellent',
    size: 'Size L',
    isNewEdit: true,
  },
  {
    id: 'prod-3',
    name: 'Vintage Denim',
    price: 1099,
    image: '/images/products/vintage-denim.jpg',
    category: 'Bottoms',
    condition: 'Good Condition',
    size: 'Size 32',
    isNewEdit: true,
  },
  {
    id: 'prod-4',
    name: 'Minimal Shoulder Bag',
    price: 1499,
    image: '/images/products/minimal-shoulder-bag.jpg',
    category: 'Accessories',
    condition: 'Like New',
    size: 'One Size',
    isNewEdit: true,
  },
  {
    id: 'prod-5',
    name: 'Floral Puff Blouse',
    price: 999,
    image: '/images/products/floral-puff-blouse.jpg',
    category: 'Tops',
    condition: 'Like New',
    size: 'Size S',
    isNewEdit: false,
  },
];
